# Generated by Django 4.0.6 on 2022-07-28 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentor', '0001_initial'),
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor'),
        ),
    ]
