# Generated by Django 4.0.6 on 2022-07-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expertise',
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.ManyToManyField(to='expertise.expertise'),
        ),
    ]
